export const tracks: { [key: string]: string } = {
  f1: "Stream of Praise - Jesus, You're In My Heart.mp3",
  f2: "Stream of Praise - Love The Lord Your God.mp3",
  "`": "test.wav",
  "1": "Bach - Brandenburg Concerto - No 1, I Allegro.mp3",
  "2": "Bach - Brandenburg Concerto - No 1, III Allegro.mp3",
  "3": "Bach - Brandenburg Concerto - No 1, IV Menuetto.mp3",
  "4": "Bach - Brandenburg Concerto - No 2, III. Allegro assai.mp3",
  "5": "Bach - Brandenburg Concerto - No 3, I. Allegro moderato.mp3",
  "6": "Bach - Brandenburg Concerto - No 3, III. Allegro.mp3",
  "7": "Bach - Brandenburg Concerto - No 4, I. Allegro.mp3",
  "8": "Bach - Brandenburg Concerto - No 4, III. Presto.mp3",
  "9": "Bach - Brandenburg Concerto - No 6, III. Allegro.mp3",
  "0": "Vivaldi - Spring I.mp3",
  "-": "Vivaldi - Spring III.mp3",
  "+": "Vivaldi - Autumn I.mp3",
  row2: "",
  q: "Tchaikovsky - Nutcracker - Overture.mp3",
  w: "Tchaikovsky - Nutcracker - Danse de la fée Dragée.mp3",
  e: "Tchaikovsky - Nutcracker - Divertissement d Trépak_danse russe.mp3",
  r: "Tchaikovsky - Nutcracker - Divertissement e Danse_des mirlitons.mp3",
  t: "Tchaikovsky - Nutcracker - Marche.mp3",
  y: "Tchaikovsky - Nutcracker - Valse des fleurs.mp3",
  u: "Shining Force II - Warrior of the Reviving Light.mp3",
  i: "Shining Force II - Welcome To Our Town.mp3",
  o: "Shining Force II - Dwarf.mp3",
  p: "Shining Force II - Martin Fowler - Elven Town.mp3",
  "[": "Shining Force II - Wings.mp3",
  "]": "Paul McCartney - Silly Love Songs.mp3",
  row3: "",
  a: "LuluKids - Pussy Cat Pussy Cat.mp3",
  s: "Beatles - Thank You Girl.mp3",
  d: "Tim Hart and Friends - The Grand Old Duke of York.mp3",
  f: "Tchaikovsky - Chanson Napolitaine Op. 39.mp3",
  g: "Bach - Minuet in G Major.mp3",
  h: "Chopin - Nocturne Op. 9 No.2.mp3",
  j: "Paul McCartney - Listen to What the Man Says.mp3",
  k: "Baby Einstein_Music Box Orchestra - Teapot.mp3",
  l: "Patty Shukla - Choo Choo Train.mp3",
  ";": "Satie - Gymnopedie No1.mp3",
  "'": "Bach - Well Tempered Clavier, Book 1.mp3",
  row4: "",
  z: "Mega Man 3 - Bcutter - Intro on Piano.mp3",
  x: "Mega Man 3 - Bcutter - Magnet Man.mp3",
  c: "Beatles - Ask Me Why.mp3",
  v: "Beatles - Words of Love.mp3",
  b: "Petra - More Power to Ya.mp3",
  n: "Petra - The Coloring Song.mp3",
  m: "Paul Taylor - Friday@5.mp3",
  ",": "Raffi - Bananaphone.mp3",
  ".": "",
  "/": "",
};
